---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: postgresql
  :database: sample_development
  :username: the_user
  :password: secrets
  :host: localhost

:test:
  <<: *defaults
  :database: sample_test

:production:
  <<: *defaults
  :database: sample_production